var data = {
    "type":"FeatureCollection",
    "features":[
        {
            "type":"Feature",
            "properties":{
                "VEHICULE_ID":1,
                "type":"Moissonneuse",
                "etat":"Utilise",
            },
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -1.448450,
                    47.970787
                ],
            }
        },
        {
            "type":"Feature",
            "properties":{
                "VEHICULE_ID":2,
                "type":"Tracteur",
                "etat":"Utilise",
            },
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -1.448450,
                    47.970787
                ],
            }
        },
    ]
}

